// Real Australian suburb data for seeding
// Data sourced from ABS, Australia Post, and OpenStreetMap

export const statesData = [
  { name: 'New South Wales', code: 'NSW', slug: 'nsw', active: true },
  { name: 'Victoria', code: 'VIC', slug: 'vic', active: true },
  { name: 'Queensland', code: 'QLD', slug: 'qld', active: true },
  { name: 'Western Australia', code: 'WA', slug: 'wa', active: true },
  { name: 'South Australia', code: 'SA', slug: 'sa', active: true },
  { name: 'Australian Capital Territory', code: 'ACT', slug: 'act', active: true },
  { name: 'Tasmania', code: 'TAS', slug: 'tas', active: true },
  { name: 'Northern Territory', code: 'NT', slug: 'nt', active: true },
];

export const suburbsData = [
  // NEW SOUTH WALES - Sydney Metro
  {
    name: 'Bondi',
    slug: 'bondi',
    postcode: '2026',
    state: 'NSW',
    stateFull: 'New South Wales',
    stateSlug: 'nsw',
    city: 'Sydney',
    latitude: -33.8908,
    longitude: 151.2743,
    priority: 10,
    active: true,
    basePrice: 395,
    premiumPrice: 595,
    prestigePrice: 995,
    description: 'Bondi is one of Australia\'s most iconic beachside suburbs, known worldwide for Bondi Beach and its vibrant coastal lifestyle. The suburb features a mix of apartments, heritage terraces, and modern developments, attracting both locals and international visitors.',
    landmarks: 'Bondi Beach, Bondi to Bronte coastal walk, Bondi Pavilion, Campbell Parade cafes and restaurants',
  },
  {
    name: 'Paddington',
    slug: 'paddington',
    postcode: '2021',
    state: 'NSW',
    stateFull: 'New South Wales',
    stateSlug: 'nsw',
    city: 'Sydney',
    latitude: -33.8844,
    longitude: 151.2295,
    priority: 10,
    active: true,
    basePrice: 395,
    premiumPrice: 595,
    prestigePrice: 995,
    description: 'Paddington is a prestigious inner-city suburb known for its Victorian terrace houses, boutique shopping along Oxford Street, and vibrant arts scene. The suburb offers easy access to the CBD while maintaining a village atmosphere.',
    landmarks: 'Oxford Street shopping, Paddington Markets, Victoria Barracks, Centennial Park nearby',
  },
  {
    name: 'Surry Hills',
    slug: 'surry-hills',
    postcode: '2010',
    state: 'NSW',
    stateFull: 'New South Wales',
    stateSlug: 'nsw',
    city: 'Sydney',
    latitude: -33.8871,
    longitude: 151.2107,
    priority: 10,
    active: true,
    basePrice: 375,
    premiumPrice: 575,
    prestigePrice: 975,
    description: 'Surry Hills is a trendy inner-city suburb famous for its cafe culture, creative industries, and vibrant nightlife. The area features a mix of converted warehouses, Victorian terraces, and modern apartments.',
    landmarks: 'Crown Street dining precinct, Surry Hills Markets, Brett Whiteley Studio, numerous art galleries',
  },
  {
    name: 'Mosman',
    slug: 'mosman',
    postcode: '2088',
    state: 'NSW',
    stateFull: 'New South Wales',
    stateSlug: 'nsw',
    city: 'Sydney',
    latitude: -33.8286,
    longitude: 151.2428,
    priority: 9,
    active: true,
    basePrice: 425,
    premiumPrice: 625,
    prestigePrice: 1095,
    description: 'Mosman is an affluent harbourside suburb on Sydney\'s Lower North Shore, known for its stunning water views, heritage homes, and upscale lifestyle. The suburb offers excellent schools and parklands.',
    landmarks: 'Taronga Zoo, Balmoral Beach, Mosman Village, Middle Head fortifications',
  },
  {
    name: 'Double Bay',
    slug: 'double-bay',
    postcode: '2028',
    state: 'NSW',
    stateFull: 'New South Wales',
    stateSlug: 'nsw',
    city: 'Sydney',
    latitude: -33.8775,
    longitude: 151.2447,
    priority: 9,
    active: true,
    basePrice: 425,
    premiumPrice: 625,
    prestigePrice: 1095,
    description: 'Double Bay is one of Sydney\'s most prestigious eastern suburbs, featuring high-end shopping, fine dining, and luxury apartments with harbour views. Known as "Double Pay" for its affluence.',
    landmarks: 'Bay Street shopping, Double Bay Marina, Redleaf Pool, boutique designer stores',
  },
  {
    name: 'Newtown',
    slug: 'newtown',
    postcode: '2042',
    state: 'NSW',
    stateFull: 'New South Wales',
    stateSlug: 'nsw',
    city: 'Sydney',
    latitude: -33.8979,
    longitude: 151.1794,
    priority: 8,
    active: true,
    basePrice: 350,
    premiumPrice: 550,
    prestigePrice: 950,
    description: 'Newtown is a bohemian inner-west suburb known for its alternative culture, street art, live music venues, and diverse dining scene. King Street is the main hub of activity.',
    landmarks: 'King Street shops and restaurants, Newtown Station, Camperdown Memorial Rest Park, street art murals',
  },
  {
    name: 'Manly',
    slug: 'manly',
    postcode: '2095',
    state: 'NSW',
    stateFull: 'New South Wales',
    stateSlug: 'nsw',
    city: 'Sydney',
    latitude: -33.7969,
    longitude: 151.2873,
    priority: 9,
    active: true,
    basePrice: 395,
    premiumPrice: 595,
    prestigePrice: 995,
    description: 'Manly is a beachside suburb on Sydney\'s Northern Beaches, accessible by ferry from Circular Quay. Known for its laid-back beach lifestyle, The Corso shopping strip, and water sports.',
    landmarks: 'Manly Beach, The Corso, Shelly Beach, Manly Wharf, North Head Sanctuary',
  },
  {
    name: 'Darlinghurst',
    slug: 'darlinghurst',
    postcode: '2010',
    state: 'NSW',
    stateFull: 'New South Wales',
    stateSlug: 'nsw',
    city: 'Sydney',
    latitude: -33.8775,
    longitude: 151.2208,
    priority: 8,
    active: true,
    basePrice: 375,
    premiumPrice: 575,
    prestigePrice: 975,
    description: 'Darlinghurst is a densely populated inner-city suburb known for its cafe culture, nightlife, and historic Victorian architecture. Located between the CBD and Paddington.',
    landmarks: 'Victoria Street cafes, Darlinghurst Courthouse, East Sydney shops, Stanley Street',
  },
  {
    name: 'Balmain',
    slug: 'balmain',
    postcode: '2041',
    state: 'NSW',
    stateFull: 'New South Wales',
    stateSlug: 'nsw',
    city: 'Sydney',
    latitude: -33.8575,
    longitude: 151.1803,
    priority: 8,
    active: true,
    basePrice: 395,
    premiumPrice: 595,
    prestigePrice: 995,
    description: 'Balmain is a historic harbourside suburb in Sydney\'s inner-west, featuring Victorian terrace houses, waterfront parks, and a thriving village atmosphere. Known for its maritime heritage.',
    landmarks: 'Darling Street shops, Balmain Markets, Elkington Park, Mort Bay Park',
  },
  {
    name: 'Coogee',
    slug: 'coogee',
    postcode: '2034',
    state: 'NSW',
    stateFull: 'New South Wales',
    stateSlug: 'nsw',
    city: 'Sydney',
    latitude: -33.9206,
    longitude: 151.2575,
    priority: 8,
    active: true,
    basePrice: 375,
    premiumPrice: 575,
    prestigePrice: 975,
    description: 'Coogee is a popular beachside suburb in Sydney\'s eastern suburbs, known for its family-friendly beach, ocean pools, and the Bondi to Coogee coastal walk. Popular with locals and tourists.',
    landmarks: 'Coogee Beach, Wylie\'s Baths, Wedding Cake Island, Coogee Pavilion',
  },

  // VICTORIA - Melbourne Metro
  {
    name: 'Toorak',
    slug: 'toorak',
    postcode: '3142',
    state: 'VIC',
    stateFull: 'Victoria',
    stateSlug: 'vic',
    city: 'Melbourne',
    latitude: -37.8406,
    longitude: 145.0128,
    priority: 10,
    active: true,
    basePrice: 425,
    premiumPrice: 625,
    prestigePrice: 1095,
    description: 'Toorak is Melbourne\'s most prestigious and affluent suburb, known for its grand Victorian and Edwardian mansions, tree-lined streets, and exclusive shopping on Toorak Road.',
    landmarks: 'Toorak Road shopping, Como House, Fawkner Park, affluent residential estates',
  },
  {
    name: 'South Yarra',
    slug: 'south-yarra',
    postcode: '3141',
    state: 'VIC',
    stateFull: 'Victoria',
    stateSlug: 'vic',
    city: 'Melbourne',
    latitude: -37.8393,
    longitude: 144.9931,
    priority: 9,
    active: true,
    basePrice: 395,
    premiumPrice: 595,
    prestigePrice: 995,
    description: 'South Yarra is a trendy inner-city suburb known for Chapel Street shopping, stylish cafes, and a mix of apartments and Victorian terraces. Close to the Royal Botanic Gardens.',
    landmarks: 'Chapel Street shopping, Como Park, Botanical Gardens nearby, Prahran Market',
  },
  {
    name: 'St Kilda',
    slug: 'st-kilda',
    postcode: '3182',
    state: 'VIC',
    stateFull: 'Victoria',
    stateSlug: 'vic',
    city: 'Melbourne',
    latitude: -37.8677,
    longitude: 144.9811,
    priority: 9,
    active: true,
    basePrice: 375,
    premiumPrice: 575,
    prestigePrice: 975,
    description: 'St Kilda is Melbourne\'s famous beachside suburb known for its bohemian atmosphere, Acland Street cake shops, Luna Park amusement park, and vibrant nightlife along Fitzroy Street.',
    landmarks: 'St Kilda Beach, Luna Park, Acland Street, St Kilda Pier, Esplanade Hotel',
  },
  {
    name: 'Fitzroy',
    slug: 'fitzroy',
    postcode: '3065',
    state: 'VIC',
    stateFull: 'Victoria',
    stateSlug: 'vic',
    city: 'Melbourne',
    latitude: -37.7992,
    longitude: 144.9789,
    priority: 8,
    active: true,
    basePrice: 375,
    premiumPrice: 575,
    prestigePrice: 975,
    description: 'Fitzroy is Melbourne\'s hipster heartland, known for its street art, vintage shops, craft breweries, and eclectic dining scene. Brunswick Street is the main thoroughfare.',
    landmarks: 'Brunswick Street bars and cafes, Rose Street Artists\' Market, Fitzroy Gardens nearby',
  },
  {
    name: 'Richmond',
    slug: 'richmond',
    postcode: '3121',
    state: 'VIC',
    stateFull: 'Victoria',
    stateSlug: 'vic',
    city: 'Melbourne',
    latitude: -37.8197,
    longitude: 144.9983,
    priority: 8,
    active: true,
    basePrice: 375,
    premiumPrice: 575,
    prestigePrice: 975,
    description: 'Richmond is a vibrant inner-city suburb known for Bridge Road shopping, Victoria Street\'s Vietnamese precinct, and being home to Richmond Football Club at the MCG.',
    landmarks: 'Bridge Road factory outlets, Victoria Street restaurants, MCG nearby, Burnley Park',
  },
  {
    name: 'Brighton',
    slug: 'brighton',
    postcode: '3186',
    state: 'VIC',
    stateFull: 'Victoria',
    stateSlug: 'vic',
    city: 'Melbourne',
    latitude: -37.9067,
    longitude: 145.0000,
    priority: 9,
    active: true,
    basePrice: 425,
    premiumPrice: 625,
    prestigePrice: 1095,
    description: 'Brighton is an affluent bayside suburb known for its iconic colorful bathing boxes, grand period homes, and family-friendly beach. Church Street offers boutique shopping.',
    landmarks: 'Brighton Beach bathing boxes, Church Street shopping, Green Point, Dendy Street Beach',
  },
  {
    name: 'Carlton',
    slug: 'carlton',
    postcode: '3053',
    state: 'VIC',
    stateFull: 'Victoria',
    stateSlug: 'vic',
    city: 'Melbourne',
    latitude: -37.7997,
    longitude: 144.9669,
    priority: 8,
    active: true,
    basePrice: 375,
    premiumPrice: 575,
    prestigePrice: 975,
    description: 'Carlton is a historic inner-city suburb known for Lygon Street\'s Italian restaurants, University of Melbourne, and beautiful Victorian architecture. Melbourne\'s Little Italy.',
    landmarks: 'Lygon Street dining, University of Melbourne, Carlton Gardens, Melbourne Museum',
  },
  {
    name: 'Prahran',
    slug: 'prahran',
    postcode: '3181',
    state: 'VIC',
    stateFull: 'Victoria',
    stateSlug: 'vic',
    city: 'Melbourne',
    latitude: -37.8506,
    longitude: 145.0003,
    priority: 8,
    active: true,
    basePrice: 375,
    premiumPrice: 575,
    prestigePrice: 975,
    description: 'Prahran is a cosmopolitan inner-city suburb known for Chapel Street shopping, Prahran Market, and vibrant nightlife. Mix of apartments, terraces, and converted warehouses.',
    landmarks: 'Chapel Street, Prahran Market, Greville Street vintage shops, numerous bars and clubs',
  },

  // QUEENSLAND - Brisbane & Gold Coast
  {
    name: 'New Farm',
    slug: 'new-farm',
    postcode: '4005',
    state: 'QLD',
    stateFull: 'Queensland',
    stateSlug: 'qld',
    city: 'Brisbane',
    latitude: -27.4678,
    longitude: 153.0497,
    priority: 9,
    active: true,
    basePrice: 350,
    premiumPrice: 550,
    prestigePrice: 950,
    description: 'New Farm is a trendy riverside suburb known for its leafy streets, Queenslander homes, and vibrant cafe culture. New Farm Park and the Powerhouse arts center are local highlights.',
    landmarks: 'New Farm Park, Brisbane Powerhouse, James Street dining, Merthyr Village',
  },
  {
    name: 'Paddington',
    slug: 'paddington-qld',
    postcode: '4064',
    state: 'QLD',
    stateFull: 'Queensland',
    stateSlug: 'qld',
    city: 'Brisbane',
    latitude: -27.4606,
    longitude: 152.9989,
    priority: 8,
    active: true,
    basePrice: 350,
    premiumPrice: 550,
    prestigePrice: 950,
    description: 'Paddington Brisbane is a historic suburb known for its antique shops along Given Terrace, renovated Queenslander homes, and village atmosphere. Close to Suncorp Stadium.',
    landmarks: 'Given Terrace antique shops, Paddington Markets, Suncorp Stadium, Latrobe Terrace cafes',
  },
  {
    name: 'West End',
    slug: 'west-end',
    postcode: '4101',
    state: 'QLD',
    stateFull: 'Queensland',
    stateSlug: 'qld',
    city: 'Brisbane',
    latitude: -27.4833,
    longitude: 153.0092,
    priority: 8,
    active: true,
    basePrice: 325,
    premiumPrice: 525,
    prestigePrice: 925,
    description: 'West End is Brisbane\'s bohemian hub, known for its multicultural community, eclectic shops, live music venues, and the popular West End Markets. Alternative and artistic vibe.',
    landmarks: 'Boundary Street shops, West End Markets, South Bank nearby, Davies Park',
  },
  {
    name: 'Fortitude Valley',
    slug: 'fortitude-valley',
    postcode: '4006',
    state: 'QLD',
    stateFull: 'Queensland',
    stateSlug: 'qld',
    city: 'Brisbane',
    latitude: -27.4567,
    longitude: 153.0356,
    priority: 8,
    active: true,
    basePrice: 325,
    premiumPrice: 525,
    prestigePrice: 925,
    description: 'Fortitude Valley is Brisbane\'s entertainment district, known for its nightlife, live music venues, Chinatown, and James Street precinct. Mix of converted warehouses and modern apartments.',
    landmarks: 'Brunswick Street Mall, Chinatown, James Street shopping, numerous bars and clubs',
  },
  {
    name: 'Surfers Paradise',
    slug: 'surfers-paradise',
    postcode: '4217',
    state: 'QLD',
    stateFull: 'Queensland',
    stateSlug: 'qld',
    city: 'Gold Coast',
    latitude: -28.0023,
    longitude: 153.4297,
    priority: 10,
    active: true,
    basePrice: 375,
    premiumPrice: 575,
    prestigePrice: 975,
    description: 'Surfers Paradise is the Gold Coast\'s iconic beachside hub, known for its high-rise skyline, patrolled beach, Cavill Avenue shopping, and year-round holiday atmosphere.',
    landmarks: 'Surfers Paradise Beach, Cavill Avenue, SkyPoint Observation Deck, The Esplanade',
  },
  {
    name: 'Broadbeach',
    slug: 'broadbeach',
    postcode: '4218',
    state: 'QLD',
    stateFull: 'Queensland',
    stateSlug: 'qld',
    city: 'Gold Coast',
    latitude: -28.0297,
    longitude: 153.4286,
    priority: 9,
    active: true,
    basePrice: 375,
    premiumPrice: 575,
    prestigePrice: 975,
    description: 'Broadbeach is a sophisticated beachside suburb known for Pacific Fair shopping center, The Star casino, and a cosmopolitan dining scene. Popular with both tourists and locals.',
    landmarks: 'Pacific Fair, The Star Gold Coast, Kurrawa Beach, Broadbeach Mall',
  },
  {
    name: 'Burleigh Heads',
    slug: 'burleigh-heads',
    postcode: '4220',
    state: 'QLD',
    stateFull: 'Queensland',
    stateSlug: 'qld',
    city: 'Gold Coast',
    latitude: -28.1025,
    longitude: 153.4508,
    priority: 9,
    active: true,
    basePrice: 375,
    premiumPrice: 575,
    prestigePrice: 975,
    description: 'Burleigh Heads is a laid-back beachside suburb known for its village vibe, James Street cafes, Burleigh Headland National Park, and excellent surf breaks.',
    landmarks: 'Burleigh Beach, Burleigh Heads National Park, James Street, Tallebudgera Creek',
  },

  // WESTERN AUSTRALIA - Perth Metro
  {
    name: 'Cottesloe',
    slug: 'cottesloe',
    postcode: '6011',
    state: 'WA',
    stateFull: 'Western Australia',
    stateSlug: 'wa',
    city: 'Perth',
    latitude: -31.9953,
    longitude: 115.7564,
    priority: 10,
    active: true,
    basePrice: 375,
    premiumPrice: 575,
    prestigePrice: 975,
    description: 'Cottesloe is Perth\'s premier beachside suburb, known for its iconic beach, Indian Ocean views, heritage homes, and the popular Cottesloe Hotel. Highly sought-after location.',
    landmarks: 'Cottesloe Beach, Cottesloe Hotel, Marine Parade, Sculpture by the Sea venue',
  },
  {
    name: 'Subiaco',
    slug: 'subiaco',
    postcode: '6008',
    state: 'WA',
    stateFull: 'Western Australia',
    stateSlug: 'wa',
    city: 'Perth',
    latitude: -31.9481,
    longitude: 115.8247,
    priority: 9,
    active: true,
    basePrice: 350,
    premiumPrice: 550,
    prestigePrice: 950,
    description: 'Subiaco is a trendy inner-city suburb known for Rokeby Road\'s cafes and boutiques, heritage architecture, and proximity to Kings Park. Popular with professionals and families.',
    landmarks: 'Rokeby Road shopping, Subiaco Markets, Subiaco Oval, Kings Park nearby',
  },
  {
    name: 'Fremantle',
    slug: 'fremantle',
    postcode: '6160',
    state: 'WA',
    stateFull: 'Western Australia',
    stateSlug: 'wa',
    city: 'Perth',
    latitude: -32.0569,
    longitude: 115.7439,
    priority: 9,
    active: true,
    basePrice: 350,
    premiumPrice: 550,
    prestigePrice: 950,
    description: 'Fremantle is a historic port city known for its well-preserved Victorian and Edwardian architecture, bustling markets, maritime heritage, and vibrant arts scene.',
    landmarks: 'Fremantle Markets, Fishing Boat Harbour, Fremantle Prison, Cappuccino Strip',
  },
  {
    name: 'Claremont',
    slug: 'claremont',
    postcode: '6010',
    state: 'WA',
    stateFull: 'Western Australia',
    stateSlug: 'wa',
    city: 'Perth',
    latitude: -31.9806,
    longitude: 115.7797,
    priority: 9,
    active: true,
    basePrice: 395,
    premiumPrice: 595,
    prestigePrice: 995,
    description: 'Claremont is an affluent suburb known for Claremont Quarter shopping, prestigious schools, and leafy streets lined with character homes. Highly desirable residential area.',
    landmarks: 'Claremont Quarter, Bayview Terrace, Freshwater Bay, Lake Claremont',
  },
  {
    name: 'Scarborough',
    slug: 'scarborough',
    postcode: '6019',
    state: 'WA',
    stateFull: 'Western Australia',
    stateSlug: 'wa',
    city: 'Perth',
    latitude: -31.8942,
    longitude: 115.7564,
    priority: 8,
    active: true,
    basePrice: 350,
    premiumPrice: 550,
    prestigePrice: 950,
    description: 'Scarborough is a revitalized beachside suburb known for its world-class beach redevelopment, surfing, and modern Esplanade precinct with cafes and restaurants.',
    landmarks: 'Scarborough Beach, The Esplanade dining, beach amphitheatre, surf breaks',
  },

  // SOUTH AUSTRALIA - Adelaide Metro
  {
    name: 'North Adelaide',
    slug: 'north-adelaide',
    postcode: '5006',
    state: 'SA',
    stateFull: 'South Australia',
    stateSlug: 'sa',
    city: 'Adelaide',
    latitude: -34.9053,
    longitude: 138.5972,
    priority: 9,
    active: true,
    basePrice: 325,
    premiumPrice: 525,
    prestigePrice: 925,
    description: 'North Adelaide is a prestigious inner suburb known for its tree-lined streets, bluestone cottages, Victorian terraces, and O\'Connell Street\'s dining and shopping precinct.',
    landmarks: 'O\'Connell Street, Adelaide Oval, Melbourne Street cafes, St Peter\'s Cathedral',
  },
  {
    name: 'Glenelg',
    slug: 'glenelg',
    postcode: '5045',
    state: 'SA',
    stateFull: 'South Australia',
    stateSlug: 'sa',
    city: 'Adelaide',
    latitude: -34.9808,
    longitude: 138.5144,
    priority: 9,
    active: true,
    basePrice: 325,
    premiumPrice: 525,
    prestigePrice: 925,
    description: 'Glenelg is Adelaide\'s premier beachside suburb, featuring a historic jetty, white sandy beach, Jetty Road shopping precinct, and the iconic tram connection to the CBD.',
    landmarks: 'Glenelg Beach, Glenelg Jetty, Jetty Road shopping, Bay Discovery Centre',
  },
  {
    name: 'Unley',
    slug: 'unley',
    postcode: '5061',
    state: 'SA',
    stateFull: 'South Australia',
    stateSlug: 'sa',
    city: 'Adelaide',
    latitude: -34.9531,
    longitude: 138.6053,
    priority: 8,
    active: true,
    basePrice: 325,
    premiumPrice: 525,
    prestigePrice: 925,
    description: 'Unley is a leafy inner-southern suburb known for King William Road\'s boutique shopping, cafes, and well-maintained character homes. Family-friendly with excellent schools.',
    landmarks: 'King William Road shopping, Unley Shopping Centre, Hyde Park, Victoria Park nearby',
  },
  {
    name: 'Norwood',
    slug: 'norwood',
    postcode: '5067',
    state: 'SA',
    stateFull: 'South Australia',
    stateSlug: 'sa',
    city: 'Adelaide',
    latitude: -34.9194,
    longitude: 138.6278,
    priority: 8,
    active: true,
    basePrice: 325,
    premiumPrice: 525,
    prestigePrice: 925,
    description: 'Norwood is a vibrant inner-eastern suburb known for The Parade\'s shopping and dining precinct, heritage architecture, and strong community atmosphere.',
    landmarks: 'The Parade Norwood, Norwood Food Hall, Norwood Concert Hall, Magill Road restaurants',
  },

  // AUSTRALIAN CAPITAL TERRITORY
  {
    name: 'Kingston',
    slug: 'kingston-act',
    postcode: '2604',
    state: 'ACT',
    stateFull: 'Australian Capital Territory',
    stateSlug: 'act',
    city: 'Canberra',
    latitude: -35.3156,
    longitude: 149.1439,
    priority: 8,
    active: true,
    basePrice: 325,
    premiumPrice: 525,
    prestigePrice: 925,
    description: 'Kingston is a vibrant inner-south suburb known for its foreshore development, cafes, boutiques, and proximity to Parliament House. Popular with young professionals.',
    landmarks: 'Kingston Foreshore, Green Square, Manuka nearby, Old Bus Depot Markets',
  },
  {
    name: 'Braddon',
    slug: 'braddon',
    postcode: '2612',
    state: 'ACT',
    stateFull: 'Australian Capital Territory',
    stateSlug: 'act',
    city: 'Canberra',
    latitude: -35.2706,
    longitude: 149.1342,
    priority: 8,
    active: true,
    basePrice: 325,
    premiumPrice: 525,
    prestigePrice: 925,
    description: 'Braddon is Canberra\'s hipster hub, known for Lonsdale Street\'s cafes, bars, and restaurants. The suburb features a mix of original cottages and modern apartments.',
    landmarks: 'Lonsdale Street dining, Haig Park, Canberra Centre nearby, Ainslie shops',
  },
  {
    name: 'Manuka',
    slug: 'manuka',
    postcode: '2603',
    state: 'ACT',
    stateFull: 'Australian Capital Territory',
    stateSlug: 'act',
    city: 'Canberra',
    latitude: -35.3194,
    longitude: 149.1347,
    priority: 8,
    active: true,
    basePrice: 325,
    premiumPrice: 525,
    prestigePrice: 925,
    description: 'Manuka is an upmarket inner-south suburb known for its boutique shopping and dining precinct, leafy streets, and proximity to Parliament House and Kingston.',
    landmarks: 'Manuka shops and restaurants, Manuka Oval, Kingston Foreshore nearby',
  },

  // TASMANIA - Hobart & Launceston
  {
    name: 'Battery Point',
    slug: 'battery-point',
    postcode: '7004',
    state: 'TAS',
    stateFull: 'Tasmania',
    stateSlug: 'tas',
    city: 'Hobart',
    latitude: -42.8936,
    longitude: 147.3336,
    priority: 9,
    active: true,
    basePrice: 295,
    premiumPrice: 495,
    prestigePrice: 895,
    description: 'Battery Point is Hobart\'s historic waterfront suburb, known for its Georgian and Victorian architecture, narrow streets, and maritime heritage. One of Tasmania\'s most desirable addresses.',
    landmarks: 'Salamanca Place, Battery Point Village, Princes Park, Arthur Circus',
  },
  {
    name: 'Sandy Bay',
    slug: 'sandy-bay',
    postcode: '7005',
    state: 'TAS',
    stateFull: 'Tasmania',
    stateSlug: 'tas',
    city: 'Hobart',
    latitude: -42.8972,
    longitude: 147.3286,
    priority: 8,
    active: true,
    basePrice: 295,
    premiumPrice: 495,
    prestigePrice: 895,
    description: 'Sandy Bay is an affluent harbourside suburb home to the University of Tasmania, Wrest Point Casino, and beautiful beaches. Mix of students and established families.',
    landmarks: 'Wrest Point, University of Tasmania, Long Beach, Sandy Bay shops',
  },
  {
    name: 'North Hobart',
    slug: 'north-hobart',
    postcode: '7000',
    state: 'TAS',
    stateFull: 'Tasmania',
    stateSlug: 'tas',
    city: 'Hobart',
    latitude: -42.8703,
    longitude: 147.3136,
    priority: 8,
    active: true,
    basePrice: 295,
    premiumPrice: 495,
    prestigePrice: 895,
    description: 'North Hobart is a vibrant inner-city suburb known for Elizabeth Street\'s restaurant strip, vintage shops, and proximity to the CBD. Popular with young professionals and foodies.',
    landmarks: 'Elizabeth Street dining, State Cinema, Republic Bar and Cafe, North Hobart Oval',
  },
  {
    name: 'South Launceston',
    slug: 'south-launceston',
    postcode: '7249',
    state: 'TAS',
    stateFull: 'Tasmania',
    stateSlug: 'tas',
    city: 'Launceston',
    latitude: -41.4419,
    longitude: 147.1447,
    priority: 7,
    active: true,
    basePrice: 275,
    premiumPrice: 475,
    prestigePrice: 875,
    description: 'South Launceston is a central suburb with a mix of heritage homes, modern developments, and convenient access to the CBD and Cataract Gorge.',
    landmarks: 'Cataract Gorge, City Park, Launceston CBD, Heritage buildings',
  },

  // NORTHERN TERRITORY - Darwin
  {
    name: 'The Gardens',
    slug: 'the-gardens',
    postcode: '0820',
    state: 'NT',
    stateFull: 'Northern Territory',
    stateSlug: 'nt',
    city: 'Darwin',
    latitude: -12.4381,
    longitude: 130.8339,
    priority: 8,
    active: true,
    basePrice: 325,
    premiumPrice: 525,
    prestigePrice: 925,
    description: 'The Gardens is an upmarket inner suburb known for its leafy streets, proximity to the Botanic Gardens, and mix of tropical-style homes. Highly sought-after location.',
    landmarks: 'George Brown Darwin Botanic Gardens, Mindil Beach nearby, Darwin Golf Club',
  },
  {
    name: 'Parap',
    slug: 'parap',
    postcode: '0820',
    state: 'NT',
    stateFull: 'Northern Territory',
    stateSlug: 'nt',
    city: 'Darwin',
    latitude: -12.4297,
    longitude: 130.8400,
    priority: 8,
    active: true,
    basePrice: 325,
    premiumPrice: 525,
    prestigePrice: 925,
    description: 'Parap is a trendy inner suburb known for Parap Village shopping precinct and the famous Parap Markets. Mix of renovated homes and modern apartments.',
    landmarks: 'Parap Markets, Parap Village, Darwin CBD nearby, Parks and reserves',
  },
  {
    name: 'Fannie Bay',
    slug: 'fannie-bay',
    postcode: '0820',
    state: 'NT',
    stateFull: 'Northern Territory',
    stateSlug: 'nt',
    city: 'Darwin',
    latitude: -12.4208,
    longitude: 130.8272,
    priority: 8,
    active: true,
    basePrice: 325,
    premiumPrice: 525,
    prestigePrice: 925,
    description: 'Fannie Bay is a prestigious coastal suburb known for its beach, East Point Reserve, and leafy residential streets. Popular with families and professionals.',
    landmarks: 'Fannie Bay Beach, East Point Reserve, Museum and Art Gallery NT, Mindil Beach Casino',
  },

  // MORE NSW - Sydney Additional
  {
    name: 'Woollahra',
    slug: 'woollahra',
    postcode: '2025',
    state: 'NSW',
    stateFull: 'New South Wales',
    stateSlug: 'nsw',
    city: 'Sydney',
    latitude: -33.8889,
    longitude: 151.2414,
    priority: 9,
    active: true,
    basePrice: 425,
    premiumPrice: 625,
    prestigePrice: 1095,
    description: 'Woollahra is an affluent eastern suburbs village known for Queen Street boutiques, upscale dining, heritage homes, and proximity to Centennial Park and Bondi.',
    landmarks: 'Queen Street shopping, Paddington Markets nearby, Centennial Park, Boutique galleries',
  },
  {
    name: 'Potts Point',
    slug: 'potts-point',
    postcode: '2011',
    state: 'NSW',
    stateFull: 'New South Wales',
    stateSlug: 'nsw',
    city: 'Sydney',
    latitude: -33.8697,
    longitude: 151.2225,
    priority: 8,
    active: true,
    basePrice: 395,
    premiumPrice: 595,
    prestigePrice: 995,
    description: 'Potts Point is a cosmopolitan harbourside suburb known for Macleay Street\'s cafes and restaurants, Art Deco apartments, and harbor views. Close to Kings Cross and the CBD.',
    landmarks: 'Macleay Street, Elizabeth Bay House, Woolloomooloo Bay nearby, Fitzroy Gardens',
  },
  {
    name: 'Pyrmont',
    slug: 'pyrmont',
    postcode: '2009',
    state: 'NSW',
    stateFull: 'New South Wales',
    stateSlug: 'nsw',
    city: 'Sydney',
    latitude: -33.8711,
    longitude: 151.1942,
    priority: 8,
    active: true,
    basePrice: 395,
    premiumPrice: 595,
    prestigePrice: 995,
    description: 'Pyrmont is a revitalized harbourside suburb known for The Star casino, converted warehouses, and proximity to Darling Harbour. Popular with professionals and investors.',
    landmarks: 'The Star, Darling Harbour, Pyrmont Bridge, Jacobs Ladder',
  },
  {
    name: 'Neutral Bay',
    slug: 'neutral-bay',
    postcode: '2089',
    state: 'NSW',
    stateFull: 'New South Wales',
    stateSlug: 'nsw',
    city: 'Sydney',
    latitude: -33.8314,
    longitude: 151.2175,
    priority: 8,
    active: true,
    basePrice: 395,
    premiumPrice: 595,
    prestigePrice: 995,
    description: 'Neutral Bay is a Lower North Shore suburb known for Military Road shops and restaurants, harbor views, and family-friendly atmosphere. Excellent schools and transport.',
    landmarks: 'Military Road shopping, Anderson Park, Neutral Bay Wharf, Kurraba Point',
  },
  {
    name: 'Cremorne',
    slug: 'cremorne',
    postcode: '2090',
    state: 'NSW',
    stateFull: 'New South Wales',
    stateSlug: 'nsw',
    city: 'Sydney',
    latitude: -33.8272,
    longitude: 151.2294,
    priority: 7,
    active: true,
    basePrice: 395,
    premiumPrice: 595,
    prestigePrice: 995,
    description: 'Cremorne is a harbourside suburb on the Lower North Shore, known for its quiet residential streets, parklands, and stunning harbor views from Cremorne Point.',
    landmarks: 'Cremorne Point Reserve, Milson Point nearby, harbor foreshore walks',
  },
  {
    name: 'Glebe',
    slug: 'glebe',
    postcode: '2037',
    state: 'NSW',
    stateFull: 'New South Wales',
    stateSlug: 'nsw',
    city: 'Sydney',
    latitude: -33.8797,
    longitude: 151.1836,
    priority: 8,
    active: true,
    basePrice: 375,
    premiumPrice: 575,
    prestigePrice: 975,
    description: 'Glebe is a bohemian inner-west suburb known for Glebe Markets, Glebe Point Road\'s eclectic shops and cafes, and its diverse, student-friendly community.',
    landmarks: 'Glebe Markets, Glebe Point Road, Sydney University nearby, Jubilee Park',
  },
  {
    name: 'Rozelle',
    slug: 'rozelle',
    postcode: '2039',
    state: 'NSW',
    stateFull: 'New South Wales',
    stateSlug: 'nsw',
    city: 'Sydney',
    latitude: -33.8622,
    longitude: 151.1711,
    priority: 7,
    active: true,
    basePrice: 375,
    premiumPrice: 575,
    prestigePrice: 975,
    description: 'Rozelle is a historic inner-west suburb known for Darling Street\'s village shopping, Rozelle Markets, and proximity to Balmain and the harbor foreshore.',
    landmarks: 'Rozelle Markets, Darling Street, Bicentennial Park, Callan Park',
  },
  {
    name: 'Bronte',
    slug: 'bronte',
    postcode: '2024',
    state: 'NSW',
    stateFull: 'New South Wales',
    stateSlug: 'nsw',
    city: 'Sydney',
    latitude: -33.9061,
    longitude: 151.2653,
    priority: 9,
    active: true,
    basePrice: 395,
    premiumPrice: 595,
    prestigePrice: 995,
    description: 'Bronte is a family-friendly beachside suburb known for Bronte Beach, the ocean pool, Bronte Park, and the Bondi to Coogee coastal walk. Strong community atmosphere.',
    landmarks: 'Bronte Beach, Bronte Baths, Bronte Park, Coastal walk',
  },
  {
    name: 'Vaucluse',
    slug: 'vaucluse',
    postcode: '2030',
    state: 'NSW',
    stateFull: 'New South Wales',
    stateSlug: 'nsw',
    city: 'Sydney',
    latitude: -33.8586,
    longitude: 151.2772,
    priority: 10,
    active: true,
    basePrice: 495,
    premiumPrice: 695,
    prestigePrice: 1295,
    description: 'Vaucluse is one of Sydney\'s most exclusive harbourside suburbs, known for multi-million dollar estates, Vaucluse House, Nielsen Park, and panoramic harbor views.',
    landmarks: 'Nielsen Park, Vaucluse House, Parsley Bay, Watsons Bay nearby',
  },
  {
    name: 'Leichhardt',
    slug: 'leichhardt',
    postcode: '2040',
    state: 'NSW',
    stateFull: 'New South Wales',
    stateSlug: 'nsw',
    city: 'Sydney',
    latitude: -33.8833,
    longitude: 151.1556,
    priority: 7,
    active: true,
    basePrice: 350,
    premiumPrice: 550,
    prestigePrice: 950,
    description: 'Leichhardt is Sydney\'s Little Italy, known for Norton Street\'s Italian restaurants and cafes, the Forum cinema, and vibrant community atmosphere in the inner-west.',
    landmarks: 'Norton Street, Leichhardt Marketplace, The Forum cinema, Italian Club',
  },

  // MORE VIC - Melbourne Additional
  {
    name: 'Armadale',
    slug: 'armadale',
    postcode: '3143',
    state: 'VIC',
    stateFull: 'Victoria',
    stateSlug: 'vic',
    city: 'Melbourne',
    latitude: -37.8564,
    longitude: 145.0186,
    priority: 9,
    active: true,
    basePrice: 425,
    premiumPrice: 625,
    prestigePrice: 1095,
    description: 'Armadale is an affluent inner suburb known for High Street\'s boutique shopping, elegant Victorian and Edwardian homes, and leafy tree-lined streets. Highly desirable location.',
    landmarks: 'High Street Armadale, Glenferrie Park, Kooyong Tennis Club nearby',
  },
  {
    name: 'Elwood',
    slug: 'elwood',
    postcode: '3184',
    state: 'VIC',
    stateFull: 'Victoria',
    stateSlug: 'vic',
    city: 'Melbourne',
    latitude: -37.8808,
    longitude: 144.9850,
    priority: 8,
    active: true,
    basePrice: 375,
    premiumPrice: 575,
    prestigePrice: 975,
    description: 'Elwood is a beachside suburb known for Elwood Beach, Ormond Esplanade cafes, and relaxed coastal lifestyle. Popular with families and professionals seeking beach proximity.',
    landmarks: 'Elwood Beach, Elwood Canal, Ormond Esplanade, Point Ormond Reserve',
  },
  {
    name: 'Hawthorn',
    slug: 'hawthorn',
    postcode: '3122',
    state: 'VIC',
    stateFull: 'Victoria',
    stateSlug: 'vic',
    city: 'Melbourne',
    latitude: -37.8219,
    longitude: 145.0381,
    priority: 8,
    active: true,
    basePrice: 395,
    premiumPrice: 595,
    prestigePrice: 995,
    description: 'Hawthorn is an established inner-eastern suburb known for Glenferrie Road shopping, excellent schools including Scotch College, and heritage architecture.',
    landmarks: 'Glenferrie Road, Swinburne University, Hawthorn Town Hall, Riversdale Road',
  },
  {
    name: 'Kew',
    slug: 'kew',
    postcode: '3101',
    state: 'VIC',
    stateFull: 'Victoria',
    stateSlug: 'vic',
    city: 'Melbourne',
    latitude: -37.8067,
    longitude: 145.0347,
    priority: 9,
    active: true,
    basePrice: 425,
    premiumPrice: 625,
    prestigePrice: 1095,
    description: 'Kew is a prestigious leafy suburb known for its grand period homes, excellent schools, and High Street village shopping. One of Melbourne\'s most desirable addresses.',
    landmarks: 'High Street Kew, Studley Park Boathouse, Kew Junction, Yarra River trails',
  },
  {
    name: 'Albert Park',
    slug: 'albert-park',
    postcode: '3206',
    state: 'VIC',
    stateFull: 'Victoria',
    stateSlug: 'vic',
    city: 'Melbourne',
    latitude: -37.8439,
    longitude: 144.9583,
    priority: 9,
    active: true,
    basePrice: 425,
    premiumPrice: 625,
    prestigePrice: 1095,
    description: 'Albert Park is an upscale inner suburb surrounding Albert Park Lake and home to the Australian Grand Prix circuit. Features Victorian terraces and modern townhouses.',
    landmarks: 'Albert Park Lake, F1 Grand Prix Circuit, Victoria Avenue, Middle Park Beach nearby',
  },
  {
    name: 'Collingwood',
    slug: 'collingwood',
    postcode: '3066',
    state: 'VIC',
    stateFull: 'Victoria',
    stateSlug: 'vic',
    city: 'Melbourne',
    latitude: -37.8044,
    longitude: 144.9908,
    priority: 8,
    active: true,
    basePrice: 350,
    premiumPrice: 550,
    prestigePrice: 950,
    description: 'Collingwood is a hip inner-city suburb known for Smith Street shops and cafes, street art, renovated warehouses, and proximity to the CBD. Popular with young professionals.',
    landmarks: 'Smith Street, Gertrude Street vintage shops, Collingwood Children\'s Farm, Grace Darling Hotel',
  },
  {
    name: 'Brunswick',
    slug: 'brunswick',
    postcode: '3056',
    state: 'VIC',
    stateFull: 'Victoria',
    stateSlug: 'vic',
    city: 'Melbourne',
    latitude: -37.7664,
    longitude: 144.9608,
    priority: 7,
    active: true,
    basePrice: 325,
    premiumPrice: 525,
    prestigePrice: 925,
    description: 'Brunswick is a diverse inner-northern suburb known for Sydney Road\'s multicultural dining, live music venues, and affordable housing. Strong arts and music scene.',
    landmarks: 'Sydney Road shops, Brunswick Street Oval, Jewell Station, numerous live music venues',
  },
  {
    name: 'Port Melbourne',
    slug: 'port-melbourne',
    postcode: '3207',
    state: 'VIC',
    stateFull: 'Victoria',
    stateSlug: 'vic',
    city: 'Melbourne',
    latitude: -37.8406,
    longitude: 144.9350,
    priority: 8,
    active: true,
    basePrice: 375,
    premiumPrice: 575,
    prestigePrice: 975,
    description: 'Port Melbourne is a bayside suburb known for Port Melbourne Beach, Bay Street shopping precinct, and converted warehouse apartments. Maritime heritage and beach lifestyle.',
    landmarks: 'Port Melbourne Beach, Bay Street, Station Pier, Princes Pier',
  },

  // MORE QLD - Brisbane & Gold Coast Additional
  {
    name: 'Teneriffe',
    slug: 'teneriffe',
    postcode: '4005',
    state: 'QLD',
    stateFull: 'Queensland',
    stateSlug: 'qld',
    city: 'Brisbane',
    latitude: -27.4528,
    longitude: 153.0497,
    priority: 9,
    active: true,
    basePrice: 375,
    premiumPrice: 575,
    prestigePrice: 975,
    description: 'Teneriffe is a trendy riverside suburb known for converted woolstores, waterfront dining at The Triffid and other venues, and proximity to the city. Popular with professionals.',
    landmarks: 'Teneriffe Woolstores, The Triffid, Commercial Road dining, Riverwalk',
  },
  {
    name: 'Bulimba',
    slug: 'bulimba',
    postcode: '4171',
    state: 'QLD',
    stateFull: 'Queensland',
    stateSlug: 'qld',
    city: 'Brisbane',
    latitude: -27.4508,
    longitude: 153.0617,
    priority: 8,
    active: true,
    basePrice: 350,
    premiumPrice: 550,
    prestigePrice: 950,
    description: 'Bulimba is an established riverside suburb known for Oxford Street\'s cafes and boutiques, Queenslander homes, and riverside parks. Strong sense of community.',
    landmarks: 'Oxford Street Bulimba, Bulimba Memorial Park, Colmslie Beach Reserve',
  },
  {
    name: 'Ascot',
    slug: 'ascot-qld',
    postcode: '4007',
    state: 'QLD',
    stateFull: 'Queensland',
    stateSlug: 'qld',
    city: 'Brisbane',
    latitude: -27.4292,
    longitude: 153.0569,
    priority: 8,
    active: true,
    basePrice: 350,
    premiumPrice: 550,
    prestigePrice: 950,
    description: 'Ascot is an upmarket inner-northern suburb known for Eagle Farm Racecourse, leafy streets with character Queenslanders, and proximity to Portside Wharf and the airport.',
    landmarks: 'Eagle Farm Racecourse, Racecourse Road dining, Portside Wharf nearby',
  },
  {
    name: 'Kangaroo Point',
    slug: 'kangaroo-point',
    postcode: '4169',
    state: 'QLD',
    stateFull: 'Queensland',
    stateSlug: 'qld',
    city: 'Brisbane',
    latitude: -27.4769,
    longitude: 153.0364,
    priority: 8,
    active: true,
    basePrice: 350,
    premiumPrice: 550,
    prestigePrice: 950,
    description: 'Kangaroo Point is an inner-city riverside suburb known for the Cliffs, Story Bridge, and spectacular city views. Popular with rock climbers and cyclists.',
    landmarks: 'Kangaroo Point Cliffs, Story Bridge, Captain Burke Park, Riverwalk',
  },
  {
    name: 'Main Beach',
    slug: 'main-beach',
    postcode: '4217',
    state: 'QLD',
    stateFull: 'Queensland',
    stateSlug: 'qld',
    city: 'Gold Coast',
    latitude: -27.9683,
    longitude: 153.4283,
    priority: 9,
    active: true,
    basePrice: 395,
    premiumPrice: 595,
    prestigePrice: 995,
    description: 'Main Beach is an exclusive northern Gold Coast suburb known for Marina Mirage shopping, Tedder Avenue dining, and luxury high-rise apartments with ocean and Broadwater views.',
    landmarks: 'Marina Mirage, Tedder Avenue, The Spit, Sea World nearby',
  },
  {
    name: 'Mermaid Beach',
    slug: 'mermaid-beach',
    postcode: '4218',
    state: 'QLD',
    stateFull: 'Queensland',
    stateSlug: 'qld',
    city: 'Gold Coast',
    latitude: -28.0450,
    longitude: 153.4358,
    priority: 8,
    active: true,
    basePrice: 375,
    premiumPrice: 575,
    prestigePrice: 975,
    description: 'Mermaid Beach is a sought-after beachside suburb known for its patrolled beach, Hedges Avenue luxury homes, and laid-back Gold Coast lifestyle.',
    landmarks: 'Mermaid Beach, Nobby Beach, Pacific Fair nearby, beachfront parks',
  },
  {
    name: 'Coolangatta',
    slug: 'coolangatta',
    postcode: '4225',
    state: 'QLD',
    stateFull: 'Queensland',
    stateSlug: 'qld',
    city: 'Gold Coast',
    latitude: -28.1681,
    longitude: 153.5367,
    priority: 9,
    active: true,
    basePrice: 375,
    premiumPrice: 575,
    prestigePrice: 975,
    description: 'Coolangatta is the southernmost Gold Coast suburb on the NSW border, known for its beautiful beaches, relaxed vibe, and Coolangatta Airport. Popular surf destination.',
    landmarks: 'Coolangatta Beach, Greenmount Beach, Point Danger, Kirra Beach',
  },

  // MORE WA - Perth Additional
  {
    name: 'Mount Lawley',
    slug: 'mount-lawley',
    postcode: '6050',
    state: 'WA',
    stateFull: 'Western Australia',
    stateSlug: 'wa',
    city: 'Perth',
    latitude: -31.9344,
    longitude: 115.8717,
    priority: 8,
    active: true,
    basePrice: 350,
    premiumPrice: 550,
    prestigePrice: 950,
    description: 'Mount Lawley is a trendy inner-city suburb known for Beaufort Street\'s cafes, bars, and restaurants, the Astor Theatre, and leafy streets with character homes.',
    landmarks: 'Beaufort Street, The Astor Theatre, Mount Lawley Golf Club, Hyde Park',
  },
  {
    name: 'Nedlands',
    slug: 'nedlands',
    postcode: '6009',
    state: 'WA',
    stateFull: 'Western Australia',
    stateSlug: 'wa',
    city: 'Perth',
    latitude: -31.9797,
    longitude: 115.8081,
    priority: 8,
    active: true,
    basePrice: 375,
    premiumPrice: 575,
    prestigePrice: 975,
    description: 'Nedlands is an affluent riverside suburb home to the University of Western Australia, leafy streets, and river views. Popular with academics and professionals.',
    landmarks: 'University of WA, Matilda Bay, Broadway shops, Point Resolution Reserve',
  },
  {
    name: 'Leederville',
    slug: 'leederville',
    postcode: '6007',
    state: 'WA',
    stateFull: 'Western Australia',
    stateSlug: 'wa',
    city: 'Perth',
    latitude: -31.9364,
    longitude: 115.8411,
    priority: 7,
    active: true,
    basePrice: 325,
    premiumPrice: 525,
    prestigePrice: 925,
    description: 'Leederville is a vibrant inner-city suburb known for Oxford Street cafes and pubs, Leederville Oval, and easy access to the CBD. Popular with young professionals.',
    landmarks: 'Oxford Street, Luna Leederville cinema, Leederville Oval, Lake Monger nearby',
  },
  {
    name: 'South Perth',
    slug: 'south-perth',
    postcode: '6151',
    state: 'WA',
    stateFull: 'Western Australia',
    stateSlug: 'wa',
    city: 'Perth',
    latitude: -31.9758,
    longitude: 115.8631,
    priority: 8,
    active: true,
    basePrice: 375,
    premiumPrice: 575,
    prestigePrice: 975,
    description: 'South Perth is a riverside suburb known for its spectacular city views from the foreshore, Perth Zoo, and family-friendly atmosphere. Easy ferry access to the CBD.',
    landmarks: 'Perth Zoo, South Perth Foreshore, Sir James Mitchell Park, Mends Street',
  },
  {
    name: 'Applecross',
    slug: 'applecross',
    postcode: '6153',
    state: 'WA',
    stateFull: 'Western Australia',
    stateSlug: 'wa',
    city: 'Perth',
    latitude: -32.0200,
    longitude: 115.8347,
    priority: 9,
    active: true,
    basePrice: 395,
    premiumPrice: 595,
    prestigePrice: 995,
    description: 'Applecross is an exclusive riverside suburb known for Canning Bridge, Riseley Street cafes, and prestige homes with river views. Highly desirable family location.',
    landmarks: 'Riseley Street, Canning Bridge, Point Walter, Applecross Jetty',
  },

  // MORE SA - Adelaide Additional
  {
    name: 'Burnside',
    slug: 'burnside',
    postcode: '5066',
    state: 'SA',
    stateFull: 'South Australia',
    stateSlug: 'sa',
    city: 'Adelaide',
    latitude: -34.9400,
    longitude: 138.6450,
    priority: 8,
    active: true,
    basePrice: 325,
    premiumPrice: 525,
    prestigePrice: 925,
    description: 'Burnside is a prestigious leafy suburb in the Adelaide foothills, known for large family homes on spacious blocks, excellent schools, and proximity to the CBD.',
    landmarks: 'Burnside Village, Hazelwood Park, Tusmore Park, Mount Osmond Road',
  },
  {
    name: 'Prospect',
    slug: 'prospect',
    postcode: '5082',
    state: 'SA',
    stateFull: 'South Australia',
    stateSlug: 'sa',
    city: 'Adelaide',
    latitude: -34.8850,
    longitude: 138.5950,
    priority: 7,
    active: true,
    basePrice: 295,
    premiumPrice: 495,
    prestigePrice: 895,
    description: 'Prospect is an inner northern suburb known for Prospect Road cafes and bars, heritage homes, and proximity to the CBD. Increasingly popular with young professionals.',
    landmarks: 'Prospect Road dining, Thomas Foods, Main North Road, Adelaide Showground nearby',
  },
  {
    name: 'Henley Beach',
    slug: 'henley-beach',
    postcode: '5022',
    state: 'SA',
    stateFull: 'South Australia',
    stateSlug: 'sa',
    city: 'Adelaide',
    latitude: -34.9200,
    longitude: 138.4933,
    priority: 8,
    active: true,
    basePrice: 325,
    premiumPrice: 525,
    prestigePrice: 925,
    description: 'Henley Beach is a popular western suburbs beachside destination known for Henley Square, the historic jetty, and Seaview Road cafes and restaurants. Family-friendly atmosphere.',
    landmarks: 'Henley Beach, Henley Square, Henley Beach Jetty, Seaview Road dining',
  },
  {
    name: 'Parkside',
    slug: 'parkside',
    postcode: '5063',
    state: 'SA',
    stateFull: 'South Australia',
    stateSlug: 'sa',
    city: 'Adelaide',
    latitude: -34.9467,
    longitude: 138.6167,
    priority: 8,
    active: true,
    basePrice: 325,
    premiumPrice: 525,
    prestigePrice: 925,
    description: 'Parkside is a leafy inner-eastern suburb adjacent to Adelaide Parklands, known for Greenhill Road shopping and cafes, and convenient city access. Popular with professionals.',
    landmarks: 'Greenhill Road, Adelaide Parklands, Veale Gardens, Eastwood Shopping Centre',
  },

  // MORE ACT - Canberra Additional
  {
    name: 'Barton',
    slug: 'barton',
    postcode: '2600',
    state: 'ACT',
    stateFull: 'Australian Capital Territory',
    stateSlug: 'act',
    city: 'Canberra',
    latitude: -35.3050,
    longitude: 149.1392,
    priority: 7,
    active: true,
    basePrice: 325,
    premiumPrice: 525,
    prestigePrice: 925,
    description: 'Barton is an inner-south suburb close to Parliament House, known for diplomatic missions, government offices, and proximity to Manuka shopping precinct.',
    landmarks: 'Telopea Park, Manuka nearby, Parliament House precinct, diplomatic missions',
  },
  {
    name: 'Civic',
    slug: 'civic',
    postcode: '2601',
    state: 'ACT',
    stateFull: 'Australian Capital Territory',
    stateSlug: 'act',
    city: 'Canberra',
    latitude: -35.2778,
    longitude: 149.1300,
    priority: 8,
    active: true,
    basePrice: 325,
    premiumPrice: 525,
    prestigePrice: 925,
    description: 'Civic is Canberra\'s city center, known for Canberra Centre shopping, cultural institutions, nightlife, and high-rise apartments. The heart of the nation\'s capital.',
    landmarks: 'Canberra Centre, Australian National University nearby, Canberra Theatre, City Walk',
  },
  {
    name: 'Dickson',
    slug: 'dickson',
    postcode: '2602',
    state: 'ACT',
    stateFull: 'Australian Capital Territory',
    stateSlug: 'act',
    city: 'Canberra',
    latitude: -35.2508,
    longitude: 149.1394,
    priority: 7,
    active: true,
    basePrice: 295,
    premiumPrice: 495,
    prestigePrice: 895,
    description: 'Dickson is a vibrant inner-north suburb known for its Asian restaurants, Dickson Tradies Club, and multicultural community. Popular dining destination.',
    landmarks: 'Woolley Street Asian restaurants, Dickson shops, Dickson Tradies, Ainslie nearby',
  },
];
