export const articles = [
  {
    slug: 'why-your-marketing-agency-cannot-tell-you-how-many-listings-they-generated',
    title: 'Why Your Marketing Agency Cannot Tell You How Many Listings They Generated',
    excerpt: 'Most agencies measure impressions, clicks, and leads. None of that pays your bills. Here is why the disconnect exists and what to do about it.',
    category: 'Strategy',
    date: 'January 2026',
    content: [
      { type: 'p', text: 'You ask your marketing agency a simple question: How many listings did your work generate last quarter?' },
      { type: 'p', text: 'They send you a report. Impressions. Clicks. Cost per lead. Maybe a graph showing leads over time. But the answer to your actual question is nowhere in the document.' },
      { type: 'p', text: 'This is not because they are hiding something. It is because they genuinely do not know.' },
      { type: 'h2', text: 'The Tracking Gap' },
      { type: 'p', text: 'Most marketing agencies track what happens before someone becomes a lead. They can tell you how many people saw your ad, how many clicked, and how many filled out a form. But the moment that lead enters your CRM, the marketing agency loses visibility.' },
      { type: 'p', text: 'They do not know if your team called them back. They do not know if the lead booked an appraisal. They do not know if the appraisal became a listing. And they certainly do not know the commission value of that listing.' },
      { type: 'p', text: 'So they report on what they can measure: the top of the funnel. And you are left guessing about whether any of it actually worked.' },
      { type: 'h2', text: 'Why This Matters More Than You Think' },
      { type: 'p', text: 'Without end-to-end tracking, every marketing decision is a guess. You might be spending $5,000 a month on a campaign that generates 50 leads but zero listings. You might be spending $2,000 on a campaign that generates 10 leads but 4 listings. Without the full picture, you cannot tell which is which.' },
      { type: 'p', text: 'We have seen agencies cut their best-performing campaigns because the lead volume looked low. We have seen agencies double down on campaigns that generated nothing but tyre-kickers. The data at the top of the funnel tells you almost nothing about what is happening at the bottom.' },
      { type: 'h2', text: 'What To Do About It' },
      { type: 'p', text: 'The fix is not complicated, but it does require discipline. You need to track every lead from first contact through to signed agency agreement. That means your CRM needs to capture the lead source. Your team needs to update the status of every lead. And someone needs to connect those numbers back to your marketing spend.' },
      { type: 'p', text: 'When you do this, the decisions become obvious. You stop guessing and start investing in what actually works.' },
      { type: 'p', text: 'That is exactly what our Profitability Audit does. We trace every marketing dollar through your pipeline and show you which investments generate listings and which generate nothing.' },
    ]
  },
  {
    slug: 'the-real-cost-of-a-lead-in-australian-real-estate-2026-benchmarks',
    title: 'The Real Cost of a Lead in Australian Real Estate: 2026 Benchmarks',
    excerpt: 'Cost per lead has increased 131% in the last decade. We break down the numbers by channel, location, and agency size.',
    category: 'Data',
    date: 'January 2026',
    content: [
      { type: 'p', text: 'If you are running a real estate agency in Australia, your cost per lead has almost certainly gone up in the last five years. But how much? And how does your number compare to the industry?' },
      { type: 'p', text: 'We have compiled data from dozens of agency audits across Australia to give you a clear picture of what leads actually cost in 2026.' },
      { type: 'h2', text: 'The Numbers' },
      { type: 'p', text: 'The average cost per lead in Australian real estate has increased 131% over the last decade. In 2016, the average agency was paying around $35 per lead across all channels. In 2026, that number sits at approximately $81.' },
      { type: 'p', text: 'But averages hide the real story. The range we see is enormous. Some agencies are generating leads for $20. Others are paying over $200. The difference comes down to three things: channel mix, geographic area, and how you define a lead.' },
      { type: 'h2', text: 'Cost Per Lead by Channel' },
      { type: 'p', text: 'Google Ads typically delivers leads between $60 and $150 depending on your market. Facebook and Instagram ads range from $25 to $80. Referral and repeat business is effectively free. Content marketing and SEO have a higher upfront cost but deliver leads at $15 to $40 once established.' },
      { type: 'p', text: 'The real estate portals sit in their own category. Portal leads tend to be cheaper per lead but convert at significantly lower rates. When you factor in conversion, portal leads often end up being the most expensive per listing.' },
      { type: 'h2', text: 'Why Cost Per Lead Is the Wrong Metric' },
      { type: 'p', text: 'Here is the thing most agencies get wrong: cost per lead is almost meaningless on its own. What matters is cost per listing. A $200 lead that converts at 10% costs you $2,000 per listing. A $30 lead that converts at 0.5% costs you $6,000 per listing.' },
      { type: 'p', text: 'The cheap leads are not always the bargain they appear to be. And the expensive leads are not always a waste. You need to track the full journey to know which is which.' },
      { type: 'p', text: 'That is why we built the Profitability Audit around cost per listing, not cost per lead. It is the only number that tells you whether your marketing is actually working.' },
    ]
  },
  {
    slug: 'three-follow-up-blind-spots-that-are-costing-you-listings',
    title: 'Three Follow-Up Blind Spots That Are Costing You Listings',
    excerpt: 'After auditing dozens of agencies, we keep finding the same three gaps in follow-up systems. Here is what they are and how to fix them.',
    category: 'Conversion',
    date: 'December 2025',
    content: [
      { type: 'p', text: 'You are generating leads. Your marketing is working. People are raising their hand and saying they are interested. But somewhere between that first enquiry and a signed agency agreement, most of them disappear.' },
      { type: 'p', text: 'After auditing dozens of agencies, we keep finding the same three blind spots. Almost every agency has at least one. Most have all three.' },
      { type: 'h2', text: 'Blind Spot 1: After-Hours Enquiries' },
      { type: 'p', text: 'More than 40% of property enquiries come in outside business hours. Evenings. Weekends. Public holidays. These are often the most motivated leads because they are thinking about selling at a time when they are not at work.' },
      { type: 'p', text: 'But most agencies do not respond until the next business day. By then, the seller has contacted two other agents. The window has closed.' },
      { type: 'p', text: 'The fix: set up an automated response that goes out within 5 minutes of any after-hours enquiry. Not a generic auto-reply. A personalised message that acknowledges their specific enquiry and sets a clear next step. Then make sure someone calls them first thing the next morning.' },
      { type: 'h2', text: 'Blind Spot 2: The Voicemail Dead End' },
      { type: 'p', text: 'Your agent calls a lead. No answer. They leave a voicemail. Then what? In most agencies, nothing. The lead goes into a black hole.' },
      { type: 'p', text: 'We have seen agencies where 60% of leads received exactly one call attempt. One. If that call went to voicemail, the lead was never contacted again.' },
      { type: 'p', text: 'The fix: implement a follow-up sequence. If the first call goes to voicemail, send a text. If no response in 24 hours, try again. Then an email. Then another call. Most leads need 5 to 7 touchpoints before they respond. One voicemail is not enough.' },
      { type: 'h2', text: 'Blind Spot 3: Partial Form Submissions' },
      { type: 'p', text: 'Someone starts filling out your contact form. They enter their name and email. Then they get distracted and never hit submit. Most agencies have no idea this is happening.' },
      { type: 'p', text: 'With the right tracking, you can capture partial submissions and follow up with those people. They were interested enough to start the form. That is a warm lead that most agencies are leaving on the table.' },
      { type: 'p', text: 'The fix: implement form abandonment tracking. Capture the data as it is entered, not just when the form is submitted. Then set up a follow-up sequence for partial submissions.' },
      { type: 'h2', text: 'The Impact' },
      { type: 'p', text: 'Fixing these three blind spots does not require more marketing spend. You are not generating more leads. You are converting more of the leads you already have. We have seen agencies increase their appraisal rate by 30 to 50% just by fixing their follow-up system.' },
    ]
  },
  {
    slug: 'independent-vs-franchise-marketing-flexibility-and-what-it-means-for-roi',
    title: 'Independent vs Franchise: Marketing Flexibility and What It Means for ROI',
    excerpt: 'Independents have more marketing freedom than franchises. Here is how to use that flexibility to win more listings.',
    category: 'Strategy',
    date: 'December 2025',
    content: [
      { type: 'p', text: 'If you run an independent real estate agency, you have one significant advantage over franchise operators that most principals underestimate: marketing flexibility.' },
      { type: 'p', text: 'Franchise agencies operate within brand guidelines. Their marketing templates are approved at head office. Their ad copy, their colours, their messaging — all controlled. This creates brand consistency, which has value. But it also creates limitations.' },
      { type: 'h2', text: 'Where Independents Win' },
      { type: 'p', text: 'An independent agency can test a new ad campaign tomorrow. A franchise agent needs to submit it for approval, wait for feedback, make changes, and resubmit. By the time the campaign is approved, the market has moved.' },
      { type: 'p', text: 'Independents can tailor their messaging to their specific market. If you operate in a beachside suburb, your marketing can speak directly to that lifestyle. A franchise template designed for national use cannot do that with the same specificity.' },
      { type: 'p', text: 'Independents can also move budget quickly. If a campaign is working, you can double the spend tomorrow. If it is not, you can kill it immediately. Franchise structures often require quarterly budget approvals.' },
      { type: 'h2', text: 'The ROI Advantage' },
      { type: 'p', text: 'This flexibility translates directly to ROI. The agencies we work with who see the fastest improvements are almost always independents. Not because they are better marketers, but because they can implement changes immediately.' },
      { type: 'p', text: 'When we identify a profit leak in an audit, an independent can fix it the same week. A franchise agent might need to work through layers of approval before making the same change.' },
      { type: 'h2', text: 'How To Use Your Flexibility' },
      { type: 'p', text: 'First, stop trying to look like a franchise. Many independents copy the marketing playbook of the big brands. Corporate photography, generic slogans, safe messaging. This is the opposite of what makes you competitive.' },
      { type: 'p', text: 'Second, test aggressively. Run three ad variations instead of one. Try different offers. Experiment with different channels. Your ability to test and iterate quickly is your biggest competitive advantage.' },
      { type: 'p', text: 'Third, measure everything. Flexibility without data is just chaos. Track every lead from first contact to signed agreement. Know your numbers. Then use your flexibility to double down on what works and cut what does not.' },
    ]
  },
  {
    slug: 'how-to-calculate-your-true-cost-per-listing',
    title: 'How to Calculate Your True Cost Per Listing',
    excerpt: 'Cost per lead is meaningless without conversion data. Here is the formula we use to calculate actual cost per signed agency agreement.',
    category: 'Data',
    date: 'November 2025',
    content: [
      { type: 'p', text: 'Every agency principal knows their cost per lead. Very few know their cost per listing. This is the number that actually matters, and calculating it is simpler than you think.' },
      { type: 'h2', text: 'The Formula' },
      { type: 'p', text: 'Cost Per Listing = Total Marketing Spend ÷ Number of Listings Generated from Marketing' },
      { type: 'p', text: 'Simple, right? The hard part is not the maths. The hard part is getting accurate numbers for the second part of that equation.' },
      { type: 'h2', text: 'Step 1: Define Your Total Marketing Spend' },
      { type: 'p', text: 'This includes everything: ad spend, agency fees, portal subscriptions, creative production, photography, signage, print materials, sponsorships. If it is money spent to generate or support new business, it counts.' },
      { type: 'p', text: 'Most agencies undercount their marketing spend by 20 to 30% because they forget about the smaller line items. Be thorough.' },
      { type: 'h2', text: 'Step 2: Track Lead Sources' },
      { type: 'p', text: 'Every lead that enters your CRM needs a source tag. Where did they come from? Google ad? Facebook? Referral? Portal? Walk-in? If you do not know where the lead came from, you cannot attribute the listing back to a marketing channel.' },
      { type: 'p', text: 'This is where most agencies fall down. Their CRM has a lead source field, but nobody fills it in consistently. Make it mandatory. No exceptions.' },
      { type: 'h2', text: 'Step 3: Track the Full Journey' },
      { type: 'p', text: 'For every lead, track: Did they respond? Did they book an appraisal? Did the appraisal happen? Did they sign? What was the listing value?' },
      { type: 'p', text: 'This gives you conversion rates at every stage. Lead to contact. Contact to appraisal. Appraisal to listing. Each stage has a drop-off rate, and each drop-off is an opportunity to improve.' },
      { type: 'h2', text: 'Step 4: Calculate by Channel' },
      { type: 'p', text: 'Do not just calculate an overall cost per listing. Calculate it for each marketing channel. You will almost certainly find that some channels are delivering listings at 3x or 4x the cost of others. That is where the real insight lives.' },
      { type: 'p', text: 'When you know your cost per listing by channel, the budget decisions become obvious. Stop guessing. Start calculating.' },
    ]
  },
  {
    slug: 'the-appraisal-to-listing-ratio-why-it-matters-more-than-lead-volume',
    title: 'The Appraisal-to-Listing Ratio: Why It Matters More Than Lead Volume',
    excerpt: 'You can double your listings without generating a single extra lead. Here is how to focus on conversion instead of volume.',
    category: 'Conversion',
    date: 'November 2025',
    content: [
      { type: 'p', text: 'Most agency principals think the path to more listings is more leads. Spend more on marketing. Generate more enquiries. Fill the top of the funnel.' },
      { type: 'p', text: 'But what if the problem is not the number of leads? What if the problem is what happens after the lead comes in?' },
      { type: 'h2', text: 'The Number Nobody Talks About' },
      { type: 'p', text: 'Your appraisal-to-listing ratio tells you what percentage of appraisals your team converts into signed agency agreements. The industry average sits around 50 to 55%. That means roughly half the appraisals your agents conduct result in nothing.' },
      { type: 'p', text: 'Think about that. Your marketing generated the lead. Your team followed up. They booked the appraisal. The agent drove to the property, spent an hour preparing, and presented. And half the time, they walked away empty-handed.' },
      { type: 'h2', text: 'Why This Ratio Matters More Than Lead Volume' },
      { type: 'p', text: 'If your team does 20 appraisals a month with a 50% conversion rate, you get 10 listings. If you improve that ratio to 70%, you get 14 listings from the same 20 appraisals. That is 4 additional listings per month without spending a single extra dollar on marketing.' },
      { type: 'p', text: 'At an average commission of $15,000 to $20,000 per listing, that is $60,000 to $80,000 in additional monthly revenue. From zero additional marketing spend.' },
      { type: 'h2', text: 'What Drives the Ratio' },
      { type: 'p', text: 'The appraisal-to-listing ratio is driven by three things: the quality of leads going into appraisals, the quality of the appraisal presentation itself, and the speed and quality of post-appraisal follow-up.' },
      { type: 'p', text: 'Lead quality is a marketing problem. If your agents are doing appraisals for people who are 18 months away from selling, the ratio will be low regardless of how good the presentation is.' },
      { type: 'p', text: 'Presentation quality is a training problem. Are your agents presenting data? Are they showing market evidence? Are they differentiating your agency from the competition?' },
      { type: 'p', text: 'Post-appraisal follow-up is a systems problem. How quickly does the agent follow up after the appraisal? What do they send? How many touchpoints before they give up?' },
      { type: 'h2', text: 'Start Measuring It' },
      { type: 'p', text: 'If you are not tracking your appraisal-to-listing ratio today, start. It is the single most impactful number in your business. Small improvements here have an outsized effect on revenue because they compound across every appraisal your team conducts.' },
    ]
  },
]
